### ISSUE TITLE
Ridge racer 3D - Graphical bugs in menu

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1661]
Nothing useful in log...

**3DS**

![ridge racer 4](https://cloud.githubusercontent.com/assets/11453507/14462145/03cefcb4-00c6-11e6-8ef2-a399b3291b5b.JPG)

![ridge racer 5](https://cloud.githubusercontent.com/assets/11453507/14462151/0877162a-00c6-11e6-83b8-aaa2f64e7780.JPG)

![ridge racer 6](https://cloud.githubusercontent.com/assets/11453507/14462157/0dffe720-00c6-11e6-9f06-792c62bb22b7.JPG)

**Citra:**

![ridge racer 1](https://cloud.githubusercontent.com/assets/11453507/14461972/1fcba0d0-00c5-11e6-9f75-c2cb337aa47c.JPG)

![ridge racer 2](https://cloud.githubusercontent.com/assets/11453507/14461975/23e914fe-00c5-11e6-8400-cbcb070b0573.JPG)

![ridge racer 3](https://cloud.githubusercontent.com/assets/11453507/14461983/28e745b6-00c5-11e6-9009-32f9d3f87a95.JPG)

**Comment by exhalatio** [comment]
Tested in db0db6a
Graphical bugs in the tunnel.
![rr3d](https://cloud.githubusercontent.com/assets/7089513/14481971/b6ff9e2c-0172-11e6-9a0d-234426ed099a.jpg)

**Comment by JayFoxRox** [comment]
I can't reproduce the bug from the first post using `master`. Can you post a log or apitrace?

---

The second bug should have its own issue.
@exhalatio: Can you remove your post and instead recreate it as a new issue please?
(There is also another bug with cars in the SW rasterizer. I'll probably create an issue about that later)

**Comment by JayFoxRox** [comment]
(Issue still exists)

**Comment by Dragios** [comment]
This can be closed. I can't bisect this because I can't obtain a release build before *31 Dec 2016*.
Compiling each and bisect in between will take a lot of time so I won't bother doing. All I can say is, this is fixed as of commit dated back f7dd8d5e816c4157ae909600fd2a7d848a1c9712.

The test build I used is the one I created myself last time as the unofficial nightly build [here](https://github.com/Dragios/Citra/releases/tag/mingw)
![Unofficial Nightly](https://user-images.githubusercontent.com/18496868/43302082-12f3f97a-919b-11e8-86e4-2e46a3d5336a.png)

**Comment by legend800** [comment]
(Issue still exists as of 7/27 Canary)

**Comment by MojoJojoDojo** [comment]
still exists lol
![image](https://user-images.githubusercontent.com/33392696/95743074-cfc11800-0c99-11eb-8c47-8a4ec8a84fbe.png)

**Comment by mrwallace888** [comment]
Wanted to bump this to say that this issue is still very much an issue on the latest nightly as of September 3, 2022.

I have to do one single race but have to restart the emulation 50+ times until it finally renders properly.

**Comment by benderscruffy** [comment]
no graphics issues for myself as in the first post
can be closed

**Comment by Dragios** [comment]
> More about this issue:
> 
>     * It happens when entering the "Machine Select" menu using the "Single Player"-"Grand Prix" mode.
>       
>       * There are hundreds of  unmapped read16/read32 and write16/write32 when using this way of entering the menu (After event select) - maybe related to Race select screen? (Also hundreds of errors when leaving the menu again (Before race select))
>       * Texture does not switch when rendering the car make (Related to [Pica: Reduce batching errors #1688](https://github.com/citra-emu/citra/pull/1688) ?) - uses font texture (A4) for rendering other HUD elements
>       * Bug occurs and most HUD elements are only white
> 
>     * It does _not_ happen when entering the "Machine Select" menu using "Single Player"-"Quick Tour".
>       
>       * Nothing weird in log
>       * Texture for car make properly selected (RGBA8)
>       * Still broken if "Grand Prix" was chosen before
>         
>         * (Texture not switched anymore)
> 
>     * Sometimes it works after visiting the "Quick Tour" menu various times before finally going all the way through with the "Grand Prix" selection, however, it seems to hang when returning to the main menu then with exactly these lines (same addresses!) repeated hundreds of times:
> 
> 
> ```
> [ 413.728059] HW.Memory <Error> core/memory.cpp:Read:137: unmapped Read8 @ 0x7CE12180
> [ 413.728077] HW.Memory <Error> core/memory.cpp:Read:137: unmapped Read8 @ 0x7CE12181
> [ 413.728094] HW.Memory <Error> core/memory.cpp:Read:137: unmapped Read8 @ 0x7CE12182
> [ 413.728112] HW.Memory <Error> core/memory.cpp:Read:137: unmapped Read8 @ 0x7CE12183
> [ 413.728133] HW.Memory <Error> core/memory.cpp:Read:137: unmapped Read8 @ 0x7CE12184
> [ 413.728153] HW.Memory <Error> core/memory.cpp:Read:137: unmapped Read8 @ 0x7CE12185
> [ 413.728167] HW.Memory <Error> core/memory.cpp:Read:137: unmapped Read8 @ 0x7CE12186
> [ 413.728180] HW.Memory <Error> core/memory.cpp:Read:137: unmapped Read8 @ 0x7CE12187
> [ 413.728198] HW.Memory <Error> core/memory.cpp:Read:137: unmapped Read32 @ 0x7CE12188
> ```
> 
> (There is also another bug with cars in the SW rasterizer. I'll probably create an issue about that later)

@benderscruffy did you actually test according to the instruction? It only happens when you select _Single Player - Grand Prix Mode_. Latest Nightly still have this issue. Please reopen the issue.

![image](https://user-images.githubusercontent.com/18496868/236654478-d55fed47-4c74-45bd-a120-941946c18ad2.png)

**Comment by benderscruffy** [comment]
ok i tested in canary

**Comment by FearlessTobi** [comment]
Reopening for the time being.
Would be great to figure out why there are conflicting reports here.

**Comment by benderscruffy** [comment]
@Dragios 
which graphics card do you have ???

**Comment by benderscruffy** [comment]
using vulkan backend the emulator crashes out now at the start of the race

**Comment by JayFoxRox** [comment]
>  Would be great to figure out why there are conflicting reports here.

Please also check for errors in the log (which would strongly indicate this is an emulation bug that is independent of graphics drivers).
Might also be worth checking if there are different versions of this game or if it could be related to savegame usage or similar.

> using vulkan backend the emulator crashes out now at the start of the race

That would be a separate bug, that should be discussed in a separate GitHub issue.

**Comment by Alejandrocaro35** [comment]
> Nothing useful in log...
> 
> **3DS**
> 
> ![ridge racer 4](https://cloud.githubusercontent.com/assets/11453507/14462145/03cefcb4-00c6-11e6-8ef2-a399b3291b5b.JPG)
> 
> ![ridge racer 5](https://cloud.githubusercontent.com/assets/11453507/14462151/0877162a-00c6-11e6-83b8-aaa2f64e7780.JPG)
> 
> ![ridge racer 6](https://cloud.githubusercontent.com/assets/11453507/14462157/0dffe720-00c6-11e6-9f06-792c62bb22b7.JPG)
> 
> **Citra:**
> 
> ![ridge racer 1](https://cloud.githubusercontent.com/assets/11453507/14461972/1fcba0d0-00c5-11e6-9f75-c2cb337aa47c.JPG)
> 
> ![ridge racer 2](https://cloud.githubusercontent.com/assets/11453507/14461975/23e914fe-00c5-11e6-8400-cbcb070b0573.JPG)
> 
> ![ridge racer 3](https://cloud.githubusercontent.com/assets/11453507/14461983/28e745b6-00c5-11e6-9009-32f9d3f87a95.JPG)

Surely what is happening is that the game is emulated with the OpenGL graphics API, which on some processors presents graphical errors. Now, with the addition of Vulkan to Citra, this error is solved. Try changing the graphic API by going to Emulation -> Configure... -> Graphics -> , within AP Settings Graphic APi change OpenGl to Vulkan. Press OK
