### ISSUE TITLE
Pokémon Virtual Console – Distorted music in game

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#2552]
Since HLE audio looping support is added to *Citra*, Virtual Console games like Pokémon started to play music. But there is one problem as reported by @wwylele in https://github.com/citra-emu/citra/pull/2422#issuecomment-273285571 which is the music playback frame is somehow distorted.

Log:
[Pokémon Yellow VC](http://pastebin.com/kbjXejVw)
[Pokémon Trading Card Game VC](http://pastebin.com/5ebU9MMr)

I have attached two music samples from 2 different Pokémon VC Game
[Pokémon Trading Card Game 3DS VC.ogg](https://github.com/Dragios/Cloud-Drive/blob/master/Pok%C3%A9mon%20Trading%20Card%20Game%203DS%20VC.ogg?raw=true)
[Pokémon Yellow 3DS VC.ogg](https://github.com/Dragios/Cloud-Drive/blob/master/Pok%C3%A9mon%20Yellow%203DS%20VC.ogg?raw=true)

Tested on latest commit which is 2889372e47624e368df0d0361cb38b8100f047dd

**Comment by MelonSpeedruns** [comment]
Just letting you know that the issue haven't changed. Tested with the latest Canary! (HEAD-b40c597)

**Comment by Dragios** [comment]
This is fixed with DSP LLE mode. Now just waiting for HLE mode to be fix. #4490.

**Comment by MojoJojoDojo** [comment]
I dunno if DSP LLE really fixes it completely.
GB/GBC games still dont sound right to me.

**Comment by FearlessTobi** [comment]
Make sure you don't have `Surround` enabled.

**Comment by legoj15** [comment]
Metroid NES on the Virtual Console sounds correct now with DSP LLE (and 3DS audio set to Stereo)

**Comment by benderscruffy** [comment]
Has this been fixed ??
Please update

**Comment by Dragios** [comment]
There are no PR related to sound fixes even up to now, so of course this issue is not fix.
