### ISSUE TITLE
Legend of Legacy Hangs on gameover

### ISSUE THREAD

**Issue by AuraOfTheDawn** [citra-emu/citra#3056]
Head - f75dd34

Upon receiving a gameover ingame, the game over text fades in, the screen fades out, the game over text fades out, and the game then drops to 0 fps and hangs indefinitely on this blackscreen. Reproduces on any game over from any fight.

Specs: 
Intel Xeon E31240
Nvidia Geforce GTX 750
8 GB Ram

[log Legend Of Legacy GameOverHang.txt](https://github.com/citra-emu/citra/files/1423948/log.Legend.Of.Legacy.GameOverHang.txt)

**Comment by benderscruffy** [comment]
using the latest nightly this has been fixed
this can be closed

**Comment by Artuvazro** [comment]
This bug has not been fixed yet. The game still freezes on game over but not on every map (checked latest version from today 2807).
It doesn't crash in the first map (Forest Ruins), but it crashes in all the other maps on game over.
