### ISSUE TITLE
New Super Mario Bros. 2 crashes in stage 6-4

### ISSUE THREAD

**Issue by FearlessTobi** [citra-emu/citra#3130]
(Intially this issue was reported by a user on the forum but because it got mostly ignored, I decided to also post it here so it at least doesn´t get forgotten.)
To reproduce the issue, simply play through stage 6-4. The crash happens in the second half of the level.
![screenshot](https://user-images.githubusercontent.com/20753089/32985210-de7614b2-ccb5-11e7-8800-3fd755b93a5c.png)
Apparently, collecting one of these coins crashes Citra.

Turning CPU/Shader Jit or HW Renderer off doesn´t prevent the issue. The crash also happens in very old builds of Citra.

I also tried to debug the issue in VS and it gave me this: 
"Exception triggered at 0x000001C8AD2090B0 in citra-qt.exe: 0xC0000005: Segmentation fault while reading at position 0x00007FEF13EAF7B0."

- Citra version: Latest Nightly (https://github.com/citra-emu/citra/commit/c810a3f3b0d8db5272bd4bd4af54becc8b9cb59e) (also happens on Canary)
-Log: https://pastebin.com/sD81PyJN
-Save file: https://drive.google.com/file/d/1XfRheZgBpLCycu3U5yYrOVSnOQizO_k2

**Comment by B3n30** [comment]
Can someone provide a save so i can look into that issue? The link to the save above is dead

**Comment by FearlessTobi** [comment]
Updated the save file link. It should work now.

**Comment by FearlessTobi** [comment]
This could be related to https://github.com/citra-emu/citra/issues/2443 because the stack trace of this issue also points to shader_interpreter.cpp, L152 (https://github.com/citra-emu/citra/blob/master/src/video_core/shader/shader_interpreter.cpp#L152)

**Comment by SigmaVirus** [comment]
I also get these crashes on New Super Mario Bros. 2 level 6-4 and Mario Kart 7 that's been reported.

I think the crashes (although random) I get in Kid Icarus - Uprising could also be related to issue #2443

Some chapters I can play through just fine and some chapters tends to crash all the time by just looking at them in a wrongful way.

I have been progressing and reached Chapter 8 - The Space Pirate Ship with various builds, however the boss battle there always seems to produce a crash either right away or midway so I guess that's the end of the line for now.

**Comment by valentinvanelslande** [comment]
![what](https://user-images.githubusercontent.com/22228082/34010644-16e58bee-e0d3-11e7-9641-b8a47e9efb7f.PNG)
crashed before collecting the coins

**Comment by valentinvanelslande** [comment]
It no longer happens in the latest Nightly.
![fixed](https://user-images.githubusercontent.com/22228082/37246189-367b3f32-246a-11e8-8716-cdeec1116b30.PNG)

**Comment by FearlessTobi** [comment]
This is not true. Please test more extensively the next time.

![crash](https://user-images.githubusercontent.com/20753089/37246537-15160c3c-24ab-11e8-9615-a0f5329390a0.png)

**Comment by benderscruffy** [comment]
still happens using the latest nightly
[citra_log.zip](https://github.com/citra-emu/citra/files/2729135/citra_log.zip)

**Comment by benderscruffy** [comment]
using the latest night doesn't crash out anymore
can be closed
