### ISSUE TITLE
Credits Crash in Mario & Luigi: Superstar Saga + Bowser’s Minions

### ISSUE THREAD

**Issue by Mid188** [citra-emu/citra#3458]
Citra Nightly Build - e51a642
So I defeat final boss in the game (Cackletta’s Soul) and escape from the castle. Credits starts to roll and the name Tetsuya Ohi (Effect Design) shows up and the plane in the backround starts to move in the different direction, I get this:

[1455.500105] HW.Memory core/memory.cpp:GetPhysicalPointer:297: unknown GetPhysicalPointer @ 0x8CBD5E36

Any help how to deal with this? It happens everytime during credits. Keep in mind it is only problem I encountered during my playthrough.

Anyways. I would appreciate your help. Thanks in advance.

System Information
Operating System: Windows 10 Home
CPU: Intel® Core™ i5-3210M CPU @ 2.50GHz 2.50 GHz
GPU: I somehow have 2 displays: Intel® HD Graphics 4000 AND NVIDIA GeForce GT 635M
Citra Version (found in title bar): Citra Nightly I HEAD-e51a642
Game: Mario & Luigi: Superstar Saga + Bowser’s Minions

I also read about posting the log, so here: 
[ 0.000000] Loader core/loader/loader.cpp:GetLoader:137: File C:\Users\Voříšek\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/001b8f00/content/00000000.app has a different type than its extension.
[ 0.110152] Frontend citra_qt/main.cpp:CheckForUpdates:464: Update check started
[ 0.256431] Frontend citra_qt/main.cpp:BootGame:604: Citra starting…
[ 0.285966] Loader core/loader/loader.cpp:GetLoader:137: File C:\Users\Voříšek\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/001b8f00/content/00000000.app has a different type than its extension.
[ 0.319129] Render.OpenGL video_core/renderer_opengl/renderer_opengl.cpp:Init:488: GL_VERSION: 3.3.0 - Build 10.18.10.4358
[ 0.319154] Render.OpenGL video_core/renderer_opengl/renderer_opengl.cpp:Init:489: GL_VENDOR: Intel
[ 0.319164] Render.OpenGL video_core/renderer_opengl/renderer_opengl.cpp:Init:490: GL_RENDERER: Intel® HD Graphics 4000
[ 0.326579] Loader core/loader/ncch.cpp:Load:159: Program ID: 00040000001B8F00
[ 0.326816] Service.FS core/file_sys/ncch_container.cpp:OpenFile:109: Failed to open C:\Users\Voříšek\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/001b8f00/content/00000000.app
[ 0.357504] Loader core/hle/kernel/process.cpp:ParseKernelCaps:114: ExHeader kernel version: 2.46
[ 0.358887] Service.CFG core/hle/service/cfg/cfg.cpp:SetPreferredRegionCode:615: Preferred region code set to 0
[ 0.375669] Service.SRV core/hle/service/sm/srv.cpp:RegisterClient:48: (STUBBED) called
[ 0.520872] Service.SRV core/hle/service/sm/srv.cpp:EnableNotification:70: (STUBBED) called
[ 0.524068] Service.APT core/hle/service/apt/apt.cpp:GetLockHandle:255: (STUBBED) called applet_attributes=0x00000000
[ 0.530554] Service.APT core/hle/service/apt/apt.cpp:SetScreenCapPostPermission:561: (STUBBED) screen_capture_post_permission=0
[ 0.531391] Service.NDM core/hle/service/ndm/ndm.cpp:OverrideDefaultDaemons:204: (STUBBED) default_daemon_bit_mask=0x0000000F
[ 0.531565] Service.NDM core/hle/service/ndm/ndm.cpp:SuspendDaemons:89: (STUBBED) daemon_bit_mask=0x00000009
[ 0.532744] Service.APT core/hle/service/apt/apt.cpp:NotifyToWait:234: (STUBBED) app_id=768
[ 0.536609] Service.APT core/hle/service/apt/apt.cpp:AppletUtility:452: (STUBBED) called command=0x00000007, input_size=0x00000004, output_size=0x00000001
[ 0.537087] Service.APT core/hle/service/apt/apt.cpp:AppletUtility:452: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001
[ 0.548065] Service.FS core/hle/service/fs/fs_user.cpp:InitializeWithSdkVersion:811: (STUBBED) called, version: 0x0B0502C8
[ 0.571207] Service.LDR core/hle/service/ldr_ro/ldr_ro.cpp:LoadCRR:169: (STUBBED) called, crr_buffer_ptr=0x08015000, crr_size=0x00001000
[ 0.574104] Service.DSP core/hle/service/dsp_dsp.cpp:LoadComponent:150: Firmware hash: 0x60af809bc5b32916
[ 0.574118] Service.DSP core/hle/service/dsp_dsp.cpp:LoadComponent:154: Structures hash: 0x3fe31c7be0d849ca
[ 0.574124] Service.DSP core/hle/service/dsp_dsp.cpp:LoadComponent:159: (STUBBED) called size=0x35388, prog_mask=0x000300FF, data_mask=0x003500FF, buffer=0x30000008
[ 0.575558] Service.DSP core/hle/service/dsp_dsp.cpp:RegisterInterruptEvents:250: Registered type=2, pipe=2, event_handle=0x0008801F
[ 0.575916] Service.DSP core/hle/service/dsp_dsp.cpp:GetSemaphoreEventHandle:176: (STUBBED) called
[ 0.576252] Service.DSP core/hle/service/dsp_dsp.cpp:SetSemaphoreMask:471: (STUBBED) called mask=0x00002000
[ 0.576745] Audio.DSP audio_core/hle/hle.cpp:PipeWrite:149: Application has requested initialization of DSP hardware
[ 0.576997] Service.DSP core/hle/service/dsp_dsp.cpp:SetSemaphore:273: (STUBBED) called
[ 0.579303] Service.DSP core/hle/service/dsp_dsp.cpp:SetSemaphore:273: (STUBBED) called
[ 0.688655] Service.GSP core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:663: called flag=00000000 process=10 thread_id=0
[ 0.707189] Kernel.SVC core/hle/kernel/svc.cpp:CreateMemoryBlock:1109: called addr=0x004B5000
[ 0.707424] Kernel.SVC core/hle/kernel/svc.cpp:CreateMemoryBlock:1109: called addr=0x004B7000
[ 0.707814] Service.PTM core/hle/service/ptm/ptm.cpp:CheckNew3DS:130: (STUBBED) called isNew3DS = 0x00000000
[ 0.707824] Service.APT core/hle/service/apt/apt.cpp:CheckNew3DSApp:726: (STUBBED) called
[ 0.866613] Service.APT core/hle/service/apt/apt.cpp:AppletUtility:452: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001
[ 0.872723] Service.APT core/hle/service/apt/apt.cpp:GetSharedFont:200: Loaded shared font by legacy method
[ 0.969723] Service.LDR core/hle/service/ldr_ro/cro_helper.cpp:ApplyStaticAnonymousSymbolToCRS:533: CRO “EtcSys” exports 0 static anonymous symbols
[ 0.971713] Service.LDR core/hle/service/ldr_ro/ldr_ro.cpp:LoadCRO:374: CRO “EtcSys” loaded at 0x004DE000, fixed_end=0x0054D000
[ 0.978453] Service.LDR core/hle/service/ldr_ro/cro_helper.cpp:ApplyStaticAnonymousSymbolToCRS:533: CRO “Title” exports 0 static anonymous symbols
[ 0.978643] Service.LDR core/hle/service/ldr_ro/ldr_ro.cpp:LoadCRO:374: CRO “Title” loaded at 0x0054E000, fixed_end=0x00550000
[ 2.574735] Frontend citra_qt/main.cpp:OnUpdateFound:477: No updates found
[ 4.082019] Service.FS core/hle/service/fs/archive.cpp:OpenLinkFile:239: (STUBBED) File command OpenLinkFile Path: [Binary: 000000000000000000000000]
[ 5.591790] Service.LDR core/hle/service/ldr_ro/ldr_ro.cpp:UnloadCRO:412: Unloading CRO “EtcSys”
[ 5.597179] Service.LDR core/hle/service/ldr_ro/ldr_ro.cpp:UnloadCRO:412: Unloading CRO "Title"
setGeometry: Unable to set geometry 461x500+453+107 on QWidgetWindow/‘ConfigureDialogWindow’. Resulting geometry: 461x576+453+107 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 423x576, maximum size: 16777215x16777215).

For some reason, the problem should show up here but it did not do that.

Lastly I will post a picture of how the citra looks when the error occurs.

![2debfb4feecec2ded6026d4cb8ed39635ccec2bc](https://user-images.githubusercontent.com/36749538/36603759-20a5194e-18bc-11e8-996b-85e7bd7496d0.png)

Both the log and the picture were done during earlier builds, so that means that problem persists even after updates. One more thing, it looks like I am not the only one with this issue, user namer ThunderVolt also confirmed that he has it too. This should be everything I can find about the issue.

**Comment by ThunderVolt5560** [comment]
I also got this issue, and my crash looks near identical to his. However, I can't get another screenshot of mine, as, admittedly, it took awhile to beat that boss.

**Comment by FearlessTobi** [comment]
Could you please provide a save file? It would make it way easier to reproduce the crash.

**Comment by Mid188** [comment]
Well here you go, I trust you know how to add it to the game.
[00000001.zip](https://github.com/citra-emu/citra/files/1754554/00000001.zip)

**Comment by Mid188** [comment]
Also sorry about closing/opening the issue. Clicked on the wrong button by accident.

**Comment by Mid188** [comment]
So... any luck?

**Comment by CesarAxe** [comment]
I played the game in January with the nightly 516 and I had the same problem in my AMD card.
My specs:
Intel Core i3-7100.
AMD Radeon R7 250 with updated driver.
Windows 10 Pro.

**Comment by 1425720626** [comment]
The last version of the Bleeding Edge release works fine for me.

**Comment by Mid188** [comment]
I officially close this thread. 1425720626 method is the right one. No crash on latest Bleeding Edge release.

**Comment by B3n30** [comment]
Can we please let this open as long as it isn't fixed in nightly. Thx

**Comment by Mid188** [comment]
Ok, sure. I don't mind.

**Comment by Dragios** [comment]
Is this fixed in nightly? If yes, please close this issue.

**Comment by datvm** [comment]
I have the same issue. Crash on credit. Anyone has save file after it? I want to play the ending for Minion.

**Comment by jroweboy** [comment]
This might have been fixed by https://github.com/citra-emu/citra/pull/2703 please download the latest nightly or canary and retest and let me know if its working now :+1:

**Comment by Dragios** [comment]
For some reason this got buried over time. So what happen? Is it fixed or not?

**Comment by Jerhomie** [comment]
I am still having the same issue. Disabling hardware shader does not fix it as suggested by others having this issue. I attached my log if that helps.
[citra_log.txt](https://github.com/citra-emu/citra/files/4534468/citra_log.txt)

**Comment by Zrego** [comment]
i just experienced the crash during a fade on the ending credits.

**Comment by Tjoma96** [comment]
Hi, same problem still exists on the latest Nighty build. Because of it crashing during the credits I’m unable to save after beating the game and access the last Bowser’s Minions levels

**Comment by Vonoox** [comment]
I have the same problem when the screen fades citra crashes

**Comment by cmitroka** [comment]
Just figured I'd check in and ask if there's any chance this is still on the radar.  My son loves this game and would love to see a fix for this.  If there's anything I can do to assist please let me know.

**Comment by poudink** [comment]
According to some comments higher here the crash doesn't happen on Citra Canary, so you could try using that.

**Comment by nf6429** [comment]
Can confirm that in newest Citra Canary, crash still happens, even with Hardware Shader/renderer on/off,

**Comment by FakeGodz** [comment]
Same here with latest nightly build

Citra 1769 and Canadry 2169

Both with messing around the graphic and other settings.

HW.Memory <Error> core/memory.cpp:GetPhysicalRef:475: unknown GetPhysicalPointer @ 0x8CBD5A36 at PC 0x001286A0 seems to be the error

This is the save file
[ML1_001.zip](https://github.com/citra-emu/citra/files/8884916/ML1_001.zip)

I only edit the save file to max out the characters after i crashed 2 times, because the next save point after that is after the credit...

**Comment by benderscruffy** [comment]
has this been fixed ??
please update

**Comment by benderscruffy** [comment]
using canary 2615
still crashes out during the credits
here is a save state a the beginning of the credits which might make it easier for any developer to look at
[00040000001B8F00.05.zip](https://github.com/citra-emu/citra/files/12567672/00040000001B8F00.05.zip)

**Comment by GPUCode** [comment]
Save states are not transferable between computers. Is there a save file near the credits instead?

**Comment by datvm** [comment]
Unfortunately it's not possible (been a few years so I may be wrong). The last save you have is before a long final boss fight. Then it crashes after that when the credit rolls.

**Comment by benderscruffy** [comment]
@GPUCode 
here is a save 
[ML1.zip](https://github.com/citra-emu/citra/files/12584142/ML1.zip)
the health and power are at the maximum so to get to the credits might only take you 5 or so minutes 
just when you get sucked in by bowser just use ultra mushrooms to get your health back up to the max

**Comment by furny48** [comment]
Hi, I'm have the problem but in Android. I went to the citra discord and they told me that I have to wait for the error to be solved with the updates, but I leave this post so you know that today (01/27/24) the problem still persists

**Comment by furny48** [comment]
I went to the citra discord and they told me that I have to wait for the error to be solved with the updates, but I leave this post so you know that today (01/27/24) the problem still persists

**Comment by xay401** [comment]
As of 2/4/24 the issue still persists
