### ISSUE TITLE
Dead Or Alive Dimensions - not working over local multiplayer

### ISSUE THREAD

**Issue by MojoJojoDojo** [citra-emu/citra#3712]
![image](https://user-images.githubusercontent.com/33392696/39547299-ce59e686-4e5f-11e8-9619-fab9e2272967.png)

When you try to start local multiplayer the game will crash/give a error message.
Citra version in the picture.
[citra_log.txt](https://github.com/citra-emu/citra/files/1968771/citra_log.txt)

**Comment by FearlessTobi** [comment]
This game uses the deprecated versions of the UDS service functions.

**Comment by B3n30** [comment]
`[  85.116415] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:163: unknown / unimplemented function 'CreateNetwork (deprecated)': port='nwm::UDS' cmd_buf={[0]=0x40402, [1]=0x0, [2]=0x0, [3]=0x1, [4]=0x15321f00, [5]=0x108a0300, [6]=0x800000, [7]=0x0, [8]=0x1000200, [9]=0x0, [10]=0x0, [11]=0x0, [12]=0x0, [13]=0x0, [14]=0x0, [15]=0x0, [16]=0x8, [17]=0x20002, [18]=0x89f990}
`

This is a game that uses the deprecated UDS stuff, which isn't implemented (or even REed yet)

Other games with that uses that deprecated part are Planet Crashers and Sonic Generations

**Comment by MojoJojoDojo** [comment]
oh man ok you are quick

**Comment by MojoJojoDojo** [comment]
btw this is the only game that crashes with UDS deprecated.
Sonic Generations didnt crash.

**Comment by B3n30** [comment]
@MojoJojoDojo Thanks for reporting, but this is an issue tracker. So the purpose is to document issues not to report them. If you find an issue either go to the forum or discord and only if you know what the issue is document it here. I also changed the title of that issue to what it actually is

**Comment by CakeLancelot** [comment]
Also affects [Slime Mori Mori Dragon Quest 3](https://github.com/citra-emu/citra-games-wiki/wiki/Slime-Mori-Mori-Dragon-Quest-3).

**Comment by Dragios** [comment]
This can be close? PR #4690 should have solve this issue

**Comment by FearlessTobi** [comment]
@MojoJojoDojo Please confirm this is fixed.

**Comment by MojoJojoDojo** [comment]
Dead Or Alive Dimensions is still not working online as you can see in that PR.

**Comment by MojoJojoDojo** [comment]
Works now so closed.
