### ISSUE TITLE
Canary build doesn't see aes_keys.txt

### ISSUE THREAD

**Issue by Demos25** [citra-emu/citra#4106]
if folder name contains non-ascii characters, like cyrillics.

**Comment by Leo626** [comment]
What folder? If you experience issues with Canary you should try to reproduce it with Nightly first.

**Comment by Leo626** [comment]
> Any folders in the in the way to citra.exe

I still don't understand. I use installer to install both Canary and Nightly and encrypted games run just fine. I manually downloaded Canary #768 and renamed the folder with a non-ASCII character and encrypted games still ran.

> Nightly doesn't have support for encrypted games yet

Yes it does.

**Comment by Demos25** [comment]
That's probably because it uses windows' path (%appdata%) if it installed by default, but in portable mode it cannot deal with non-ascii chars in the path, it seems

**Comment by Demos25** [comment]
for example
```
[   0.343349] Frontend <Info> citra_qt/main.cpp:GMainWindow:147: Citra Version: Nightly #907  | HEAD-516be14
[   0.544061] Loader <Debug> core/loader/loader.cpp:GetLoader:142: Loading file E:\Download\Citra/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/00164800/content/00000001.app as NCCH...
[   0.544117] Common.Filesystem <Debug> common/file_util.cpp:CreateFullPath:198: path exists E:\Download\Citra/user/sysdata/aes_keys.txt
[   0.544510] Service.FS <Debug> core/file_sys/ncch_container.cpp:Load:186: Secure2 crypto
[   0.544512] Loader <Debug> core/file_sys/ncch_container.cpp:Load:219: NCCH version 0/2
[   0.544525] Service.FS <Debug> core/file_sys/ncch_container.cpp:Load:296: Name:                        niji_loc
[   0.544747] Service.FS <Debug> core/file_sys/ncch_container.cpp:Load:297: Program ID:                  0004000E00164800
```

**with non-ascii chars in the path (Citra-кириллица)**
```
[   0.348556] Frontend <Info> citra_qt/main.cpp:GMainWindow:147: Citra Version: Nightly #907  | HEAD-516be14
[   0.363277] Frontend <Warning> citra_qt/main.cpp:CheckForUpdates:564: Unable to start check for updates
[   0.609827] Loader <Debug> core/loader/loader.cpp:GetLoader:142: Loading file E:\Download\Citra-кириллица/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/00164800/content/00000001.app as NCCH...
[   0.609896] Common.Filesystem <Debug> common/file_util.cpp:CreateFullPath:198: path exists E:\Download\Citra-кириллица/user/sysdata/aes_keys.txt
[   0.610043] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:175: Secure1 KeyX missing
[   0.610141] Service.FS <Debug> core/file_sys/ncch_container.cpp:Load:186: Secure2 crypto
[   0.610274] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:189: Secure2 KeyX missing
```

**Comment by Leo626** [comment]
Verified this. This happens in Nightly as well. You shouldn't report issues with Canary unless Nightly is unaffected and should only be for the PR that caused the regression. The correct title should be - Unable to load aes_keys.txt in portable mode if named with non-ASCII characters. Your original post does not mention portable mode and an example.

**Comment by zhaowenlan1779** [comment]
Changed the title for you..

**Comment by wwylele** [comment]
Is this fixed with #4253?

**Comment by Sincasios** [comment]
This error is still present in december 2022.

Citra can't load"aes_keys.txt" (and I don't know if other things) from path with accents. Games doesn't have this problem (If you bypass the aes_keys.txt problem, you can load games from path with accents).

I had aes_keys.txt in D:\Emulación\Citra\user\sysdata\aes_keys.txt and Citra can't load the keys (the games appears unreadable). If you move "Citra" folder to "D:\ they work fine.
