### ISSUE TITLE
Running effect on Fire Emblem: Shadows of Valentia not properly emulated

### ISSUE THREAD

**Issue by LexLight** [citra-emu/citra#6434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1881

### Description of Issue

In the dungeons, when Alm (and probably Celica) run away, the image gets darker than before, and after you get into a fight on the dungeon, the effect of darkness gets substituted by a picture of the battle, difficulting the navigation through the dungeons.

Here's a video of both effects, which I've edited to showcase mainly both of the effects that I've mentioned before, with the ending of the battle being shown to demonstrate the second effect:
https://streamable.com/zeqyk9

### Expected Behavior

A running effect, like it's shown on this video, at 1:03 :
https://youtu.be/ivLU-39jgOA?t=63

### Reproduction Steps

1. Go to a dungeon with either Alm or Celica.
2. Press B to run and you'll see the first effect previously mentioned.
3. Enter into a fight with a monster (no matter if you win or you run away from it).
4. Press B to run and you'll see the second effect previously mentioned.

Here's my save file for the game, just pick the Chapter2 one (the most recent one), which has Alm onto a dungeon in the map, just enter into it, go to the "Explore" option, and do those steps.
[FE SoT Saves.zip](https://github.com/citra-emu/citra/files/11213972/FE.SoT.Saves.zip)

### Log File

Here's a log file that I made when I recorded the attatched video.
[citra_log.txt](https://github.com/citra-emu/citra/files/11213981/citra_log.txt)

### System Configuration

CPU: Ryzen 3700x
GPU/Driver: nVidia GeForce RTX 2070 Super, 531.41.
RAM: 16 GB (8x2 at 3200 MHz)
OS: Windows 10, version 21H2.

**Comment by SachinVin** [comment]
The log file is incomplete. Make sure you follow the steps carefully:

Open Citra, then go to File>Open Citra Folder (Citra>Open Citra Folder if on MacOS) and open up the log folder. Now keep that open in the background.
Launch your game and encounter the problem; crash/slowdown/glitch and close Citra if it doesn’t do so by itself. Do not restart Citra as that will wipe the log of important information!

**Comment by LexLight** [comment]
Okay, here's a new log, I hope that it's better and more useful, through.
[citra_log.txt](https://github.com/citra-emu/citra/files/11290329/citra_log.txt)

**Comment by GPUCode** [comment]
Has this been fixed now?

**Comment by LexLight** [comment]
> Has this been fixed now?

In the lastest Nightly, nope, the second effect (the running one) is still not being shown on OpenGL, on Vulkan, there's a very noticeable graphical glitch, here's it:
https://streamable.com/gwrsiw

And here's the log:
[citra_log.txt](https://github.com/citra-emu/citra/files/12620920/citra_log.txt)

The same with both backends (respectively) happen on Canary, too.

**Comment by LexLight** [comment]
Sorry for the "closed this", it was an error.

**Comment by ilikepizza107** [comment]
Can confirm it's still happening as of today

**Comment by LexLight** [comment]
In the Software render, the effect's properly rendered, but it's still not properly rendered neither on OpenGL nor on Vulkan.

**Comment by GPUCode** [comment]
This appears to be a texture cache issue, the game is intending to use a framebuffer to render the effect, but it receives a completely unrelated texture instead. It works in software renderer as there is no texture caching there
