### ISSUE TITLE
Nearest Neighbor texture filtering no longer functional

### ISSUE THREAD

**Issue by gnesthenic** [citra-emu/citra#6462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1887

### Description of Issue

When texture filtering is set to Nearest Neighbor, the textures look as if the texture filtering were set to "none". This is true across multiple games.

### Expected Behavior

Changing the texture filtering from "none" to Nearest Neighbor should change the appearance of textures to look more pixelly/crispy and less blurry.

### Reproduction Steps

In either Configure or Configure Current Game, change the texture filtering back-and-forth between "none" and Nearest Neighbor. You may also wish to change to other filtering options to see that the textures should be visibly different. It is easiest to notice these changes in some in-game menus.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11303052/citra_log.txt)

### System Configuration

CPU: AMD Ryzen 7 5800HS with Radeon Graphics 3.20 GHz
GPU/Driver: NVIDIA GeForce RTX 3050 Ti
RAM: 16.0 GB (15.4 GB usable)
OS: Windows 11 Home 22H2 build 22621.1555

**Comment by FearlessTobi** [comment]
Should be fixed in the latest Nightly build.

**Comment by VineST** [comment]
I'm still seeing this on nightly 1998. Ironically, some textures in XYORAS (namely status indicators and world/pokemon texture maps) lose the linear filtering when the setting is on None instead of Nearest.
