### ISSUE TITLE
Vulkan initialization failed during boot

### ISSUE THREAD

**Issue by Grant12311** [citra-emu/citra#7046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2005 Flatpak

### Description of Issue

When I start Citra, I get a popup saying "Vulkan initialization failed during boot. Your GPU may not support Vulkan 1.1, or you do not have the latest graphics driver." I know this isn't true. I'm running Ubuntu 22.04 with Mesa 23.0.4 and Vulkan 1.3.211. This issue did not occur last time I used Citra (some time ago). Manually selecting "Vulkan" in the lower left corner caused Citra to crash when loading a game.

### Expected Behavior

For no popup to occur and for games to work properly with Vulkan.

### Reproduction Steps

Open Citra.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12836198/citra_log.txt)

### System Configuration

CPU: AMD Ryzen 7 5700U with Radeon Graphics
GPU/Driver: Integrated graphics with Mesa 23.0.4
RAM: 16GB
OS: Ubuntu 22.04

**Comment by TGP17** [comment]
Are you on Wayland or X11?

**Comment by Grant12311** [comment]
Wayland. Default for Ubuntu 22.04.

**Comment by TGP17** [comment]
That's a known issue with Citra Vulkan + Wayland.
https://github.com/citra-emu/citra/issues/6987
You can either use the flatpak through XWayland or use our AppImage or our installer from our website, which installs and handles Updates for the AppImage, which runs by default with XWayland.

**Comment by Steveice10** [comment]
> That's a known issue with Citra Vulkan + Wayland. #6987 You can either use the flatpak through XWayland or use our AppImage or our installer from our website, which installs and handles Updates for the AppImage, which runs by default with XWayland.

This shouldn't apply anymore. The flatpak is set up to only use XWayland.

**Comment by Grant12311** [comment]
Yes, I checked and Citra is indeed running under XWayland. Wayland permissions are disabled for it actually, and not by me.

**Comment by TGP17** [comment]
Oh didn't know that the flatpak is already updated, in that case I'd still suggest trying the AppImage for testing. AppImages uses system graphics drivers, while the flatpak uses the ones provided by flatpak

**Comment by TGP17** [comment]
You can scroll down to manual downloads and click on the tux icon to download it. The Linux setup would install it, but that shouldn't be necessary if you just want to test if the AppImage has the same problem. Make the citra-qt.AppImage executable and start the AppImage once it's downloaded to open it.

**Comment by Grant12311** [comment]
It seems to work properly with the AppImage. Is there any way for me to easily import everything from the Flatpak for the time begin while things are broken?

**Comment by Steveice10** [comment]
Out of curiosity do you have the ‘VK_ICD_FILENAMES’ environment variable set (‘echo $VK_ICD_FILENAMES’ prints a non empty line if it is set)? I’ve heard this can cause issues with flatpak.

For your saves if you can at least open the flatpak Citra, you should be able to use File -> Open Citra Folder to locate the flatpak’s files, then copy your data over to the equivalent folder in the AppImage Citra.

**Comment by Grant12311** [comment]
This is what I get from the echo. 
```
/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json
```

**Comment by Steveice10** [comment]
Thanks, could you try doing the following in your terminal to launch Citra:

```
unset VK_ICD_FILENAMES
flatpak run org.citra_emu.citra
```

**Comment by Grant12311** [comment]
That worked! Do you know why exactly?

**Comment by Steveice10** [comment]
Basically the `VK_ICD_FILENAMES` tells the Vulkan loader where to find details on your driver. Within the flatpak sandbox environment your host drivers don't exist, so it's pointing to a non-existent file as far as Citra is concerned. Unsetting the variable allows it to load the flatpak provided Mesa drivers instread.

I'll have to see if there's something we can do to prevent `VK_ICD_FILENAMES` from leaking into the flatpak environment.

**Comment by Grant12311** [comment]
I have it working now by adding this to the front of the command in the .desktop file that launches the flatpak. Everything seems good as a stopgap solution. 
```
env -u VK_ICD_FILENAMES 
```

**Comment by Steveice10** [comment]
Yeah that's what I'm planning on adding to the flatpak for now, longer term I'm also opening a PR to flatpak itself to exclude those variables from the sandbox environment. I'll close this out once at least the workaround is in our flatpak.

**Comment by Steveice10** [comment]
Should be fixed once Nightly 2009 is up on Flathub.

**Comment by Grant12311** [comment]
I can confirm this issue is still present on 2009 without my work around.

**Comment by Steveice10** [comment]
Can you check that your desktop file

**Comment by Grant12311** [comment]
It says 2009 in the window title. Is that enough?

**Comment by Steveice10** [comment]
No, you need to actually check the desktop file contents.

**Comment by Grant12311** [comment]
Gotcha. This is what I'm seeing under "Exec", omitting my modification. 
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=citra-qt --file-forwarding org.citra_emu.citra @@ %f @@
```

**Comment by Steveice10** [comment]
‘—command=citra-qt’ needs to be updated to ‘—command=citra-launcher’

**Comment by Grant12311** [comment]
I'll that that. Would my modification have kept flatpak from updating the .desktop file or is that a separate issue? I definitely didn't make that change myself.

**Comment by Grant12311** [comment]
It seems to be working with citra-launcher without the mitigation. So everything seems good. Why did that fix it?

**Comment by Steveice10** [comment]
There’s a new launcher script that handles, among other things, stripping away the environment variables we don’t want. I assume that because the desktop file was modified manually, flatpak didn’t automatically update it.
